server:
  port: 8080  # Port for the gateway
#proxy representant local de l'objet distant
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: command-service
          uri: lb://command-service
          predicates:
            - Path=/my_store/api/commande/**
          filters:
            - StripPrefix=1

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/my_store/api/paiment/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true